### ISSUE TITLE
[Platforms] Boil the list of frameworks down and change the text to be recommendations

### ISSUE THREAD

**Issue by swilliams** [Tallwave/guidelines#14]
On the [platforms page](https://tallwave.github.io/guidelines/Platforms), there's a long list of the libraries we use. Let's change this more into a recommendation. Like if a client came to you and said "how should I make my marketing site?" what would you recommend? See if you can knock it down to less than 5 libraries, and then link to them and add a bit of text as to why we recommend them.

**Comment by isiegel** [comment]
I made some edits and created a pull request, thanks.

**Comment by swilliams** [comment]
@isiegel I don't see it... got a URL?

**Comment by isiegel** [comment]
Please check again, thanks.

https://github.com/Tallwave/guidelines/pull/15/files
