### ISSUE TITLE
Team: Tips and tricks about working remotely

### ISSUE THREAD

**Issue by mmislam101** [Tallwave/guidelines#33]
Two good POVs on the idea:
1. From the perspective of a remote employee
2. From the perspective of someone in the office

How do we keep everyone engaged and part of the team?
What life is like for full time remote.

**Comment by mmislam101** [comment]
Some contention on whether this will be a fluff section or not. So only if there's real value to add in this section.

**Comment by swilliams** [comment]
Put it under the Team page. I can see two good POVs on the idea:

1. From the perspective of a remote employee
2. From the perspective of someone in the office

How do we keep everyone engaged and part of the team?

**Comment by swilliams** [comment]
[I think this is in there](https://tallwave.github.io/guidelines/Team/Working-Remote), right?

**Comment by krantzinator** [comment]
@swilliams That it is!
