### ISSUE TITLE
note on deploying workers

### ISSUE THREAD

**Issue by mmislam101** [Tallwave/guidelines#48]
Add document here: https://drive.google.com/open?id=1_K374OwYTTIuRICUPaqVBgVq0y2Zyb7Q

Here are some of the notes that I wrote:

"Terminal Commands:
eb list - lists all apps/instances eb use { desired instance } - navigates to desired instance eb deploy - deploys instance eb log - downloads logs to see console.log statements for debugging purposes
In AWS dashboard:
Add env variables after you create a new instance and it has healthy (green) status Make sure to leave a blank key-valu pair at end
Go to the list view of all instances running, select where to deploy the code in the list by checking the box, click on ‘deploy’ and a drop down list should display. Select the instance to deploy and then apply the changes."

**Comment by swilliams** [comment]
I don't necessarily know if the guidelines are the right place for this... We should definitely keep track of this kind of documentation, but I don't know if it's the right thing for the public docs. Open for discussion.

**Comment by mmislam101** [comment]
@vinnieking06 I think you originally opened this issue on an LH dashboard. I agree with @swilliams that it shouldn't go in the guidelines. Could you instead create a google doc here:
https://drive.google.com/drive/folders/1_K374OwYTTIuRICUPaqVBgVq0y2Zyb7Q

Thanks

**Comment by vinnieking06** [comment]
@mmislam101 yep, no problem
