### ISSUE TITLE
Create PR template

### ISSUE THREAD

**Issue by krantzinator** [Tallwave/guidelines#51]
[A PR template can be saved in GitHub](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/). This would allow us to have consistency in what we note in PRs across Tallwave projects (it would need to be saved in each repo of course, but I think we can handle it).

Proposed template below. Chime in with general thoughts or specific edits as you see fit.

## Description
What is the feature or bug at a high level?

### Things done
- thing 1
- thing 2

---[Optional items; delete if unused]---

### How to test
- steps to verify feature works

### Tech debt removed/added
- things

### Help requested
- any items you haven't asked for help on yet that you want to make sure people don't miss in their review?

**Comment by TinaHeiligers** [comment]
In the 'Code cleanup OR...' section, we can include an optional topic for known issues that become tech debt. This is especially useful when working under pressure to 'just get stuff done'.

**Comment by TinaHeiligers** [comment]
@krantzinator It may be blunt but it's to the point!

**Comment by swilliams** [comment]
I think "Things done" should be required, and the rest of the sections should be optional, since a PR may not necessarily have all of those. 

I really like this idea and I think we'll get value out of this template, but we want to be careful not to over-engineer and introduce friction in the process.

We should look at [Issue Templates](https://help.github.com/articles/about-issue-and-pull-request-templates/) next.

**Comment by krantzinator** [comment]
@swilliams @TinaHeiligers i updated the suggested template in my first comment above - thoughts?

**Comment by TinaHeiligers** [comment]
@krantzinator  I like the updated version

**Comment by swilliams** [comment]
@krantzinator Looks great! :shipit:

**Comment by mmislam101** [comment]
@krantzinator This is awesome. Thanks

I've had uses for some other optional headings:
- **Resolves Bug/Issue**. For when the PR resolves a bug which is an issue item in another repo
- **Dependent, child, parent, group**. This is just an idea, but later maybe @swilliams github scrubber can use these sections to tie tickets together for reporting.

**Comment by krantzinator** [comment]
@mmislam101 i like the "Resolves bug/issue" add; i'm not sure where it should go though. for PSCU, i like it in the title of the PR because we use Jira so all of our tickets are there, and the best way for me to find a "linked" ticket is to look at the list of PRs for the Jira ticket number.
obviously for github issues, linking inside the issue works great.
thoughts?

**Comment by mmislam101** [comment]
@krantzinator Yah people can add it if they need it.

**Comment by swilliams** [comment]
@blacknight811 Please review this too :)
